//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUserManagaement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherFirstName { get; set; }
        public string FatherMiddleName { get; set; }
        public string FatherLastName { get; set; }
        public string MotherFirstName { get; set; }
        public string MotherMiddleName { get; set; }
        public string MotherLastName { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public string HighestEducation { get; set; }
        public string Branch { get; set; }
        public string YearOfPassout { get; set; }
        public string SecondarySchoolName { get; set; }
        public string HigherSecondarySchoolName { get; set; }
        public string BTechCollegeName { get; set; }
        public string MTechCollegeName { get; set; }
        public string SecondaryMarks { get; set; }
        public string HigherSecondaryMarks { get; set; }
        public string BTechMarks { get; set; }
        public string MTechMarks { get; set; }
        public string ProfilePhoto { get; set; }
        public string Aadharcard { get; set; }
        public string MyResume { get; set; }
        public string GuidProfilePhoto { get; set; }
        public string GuidAadharcard { get; set; }
        public string GuidMyResume { get; set; }
        public string AboutMyself { get; set; }
        public string Hobbies { get; set; }
    }
}
