DECLARE s1 CURSOR SCROLL FOR SELECT * FROM employee;

open s1

FETCH FIRST FROM s1
FETCH LAST FROM s1
FETCH NEXT FROM s1
FETCH PRIOR FROM s1
FETCH ABSOLUTE 7 FROM s1
FETCH RELATIVE -1 FROM s1

close s1

DEALLOCATE s1